# represents infinity:
INFINITY = float('inf')

# MOUSE CLICKS
LEFT_MOUSE_CLICK = 0
MID_MOUSE_CLICK = 1
RIGHT_MOUSE_CLICK = 2

# RESOLUTION
BLOCK_SIZE = 10
WIDTH = 500
HEIGHT = 350
# ROWS = HEIGHT // BLOCK_SIZE
# COLS = WIDTH // BLOCK_SIZE
ROWS = COLS = 3
# COLORS (RGB):
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREY = (160, 160, 160)
